### ISSUE TITLE
Cannot refresh data for `taxa_tree_gbif`

### ISSUE THREAD

**Issue by grantfitzsimmons** [maxxxxxdlp/phylogenetic_tree#6]
```
~ $ cd /home/specify/taxa_tree_gbif/back_end/ && /home/specify/venv/bin/python3
refresh_data.py
Config
Preparation
Downloading meta data
Downloading the archive
Unzipping the file
Traceback (most recent call last):
  File "/home/specify/taxa_tree_gbif/back_end/refresh_data.py", line 69, in <module>
    with ZipFile(archive_name, 'r') as zip_file:
  File "/usr/local/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

I am getting `zipfile.BadZipFile: File is not a zip file`

**Comment by maxpatiiuk** [comment]
Seems like GBIF changed their API. I will take a look
